; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:mhetesp32devkit]
;platform = espressif32
;board = mhetesp32devkit
;framework = arduino


; --- Shared Configuration ---
[env]
framework = arduino

; --- Environment 1: Your ESP32 ---
[env:esp32dev]
platform = espressif32
board = esp32dev
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.6
monitor_speed=115200

; --- Environment 2: Your Arduino Mega (Left untouched) ---
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
lib_deps =
    arduino-libraries/Servo @ ^1.2.1

monitor_speed=115200